package com.pondersource.solidcontacts.data.local

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.withContext
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Where full-size contact photos live: on disk, not in the database.
 *
 * SQLite hands a row to the app through a 2 MB cursor window, so a photo stored in the contact
 * row makes that contact unreadable once the image is large enough — the row cannot be selected
 * at all, and every query that touches it throws. Files have no such ceiling, so the database
 * keeps only the few-kilobyte thumbnail and the real image sits here.
 */
@Singleton
class PhotoStore @Inject constructor(
    @param:ApplicationContext private val context: Context,
    private val io: CoroutineDispatcher,
) {

    private val directory: File
        get() = File(context.filesDir, "contact-photos").apply { mkdirs() }

    suspend fun read(contactId: String): ByteArray? = withContext(io) {
        val file = fileFor(contactId)
        if (file.exists()) runCatching { file.readBytes() }.getOrNull() else null
    }

    suspend fun write(contactId: String, bytes: ByteArray) = withContext(io) {
        runCatching { fileFor(contactId).writeBytes(bytes) }
        Unit
    }

    suspend fun delete(contactId: String) = withContext(io) {
        runCatching { fileFor(contactId).delete() }
        Unit
    }

    /** Drops every stored photo, for disconnecting the account. */
    suspend fun clear() = withContext(io) {
        runCatching { directory.deleteRecursively() }
        Unit
    }

    /** Local ids are generated by this app, but sanitise anyway: this value names a file. */
    private fun fileFor(contactId: String): File =
        File(directory, contactId.replace(Regex("[^A-Za-z0-9._-]"), "_"))
}
